Ft mobile menu
freddykaberuka/portfolio pull request #9
Opened 2022-04-12 12:56 UTC by freddykaberuka

## Completed Task

- add dynamic Menu bar
- add hamburger button, the mobile menu appears.
- add close (X) button, the mobile menu disappears.
- user clicks (or taps) any of the mobile menu options, the mobile menu disappears.
- user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed

2022-04-12 16:02 UTC, ShadyShawkat requested changes
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-12 16:02 UTC, ShadyShawkat commented on index.html
>              </div>
- Please try to stick as much as possible to the Figma design, which includes:
  - [x] Adding the blur effect on the background to match the Figma design.
  - [x] Editing the `x` button so that it looks like the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/163002088-2f03728e-592c-4bbf-96ae-f9f77e29bde4.png) | ![image](https://user-images.githubusercontent.com/62290545/163002033-ef3135da-77f1-40da-bbda-43b9f1e43916.png) |

2022-04-12 16:02 UTC, ShadyShawkat commented on index.html
> +                    <div class="bar3"></div>
- [x] Kindly add the `x` button to the modal instead of using the hamburger menu which can cause the following behavior.
![chrome-capture](https://user-images.githubusercontent.com/62290545/163004246-d9d34159-2d07-449f-9a42-a3dcc4c7b3bf.gif)

2022-04-16 13:35 UTC, phelian23 approved these changes
Hi @freddykaberuka, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-17 13:12 UTC, merged